# =================================================================================================
#     Reference Genome
# =================================================================================================

parents: ../Data/Lists
genome: ../Data/Practice_Data/Genome/small_subset_tall_fescue_genome.fa

# =================================================================================================
#     Directory Paths
# =================================================================================================
paths:
  genomepath: ../Data/Practice_Data/Genome
  progeny: ../Data/Practice_Data/Progeny


# =================================================================================================
#     Progeny lists
# =================================================================================================

# This is a key that turns the long file names into the numerical names for the progeny
progeny_key: ../Data/Lists/progeny_key.dic

# =================================================================================================
#     Indexing params
# =================================================================================================
bwa:
  index: bwtsw

# =================================================================================================
#     Progeny 
# =================================================================================================


# To call from this file you basicaly put brackets until you reach the variable you need
# ex: in the params part use [ref][fasta], then call it with params.x
