# =================================================================================================
#     Reference Genome
# =================================================================================================

genome: ../Data/Real_Data/Genome/tall_fescuev0.1.fa
idx: 


# =================================================================================================
#     Directory Paths
# =================================================================================================
paths:
  genomepath: ../Data/Real_Data/Genome/
  progeny: ../Data/Real_Data/Progeny/
  parents: ../Data/Real_Data/Parents/
  mapped_reads: ../Data/Real_Data/Mapped_Reads/
  mapped_reads_parents: ../Data/Real_Data/Mapped_Reads_Parents/
  vcfs: ../Data/Real_Data/VCFs/
  vcfs_parents: ../Data/Real_Data/VCFs_Parents/

# =================================================================================================
#     Functions
# =================================================================================================
functions:
  dic_function: dic_functions.py


# =================================================================================================
#     Progeny lists
# =================================================================================================

# This is a key that turns the long file names into the numerical names for the progeny
lists:
  progeny_key: ../Data/Real_Data/Lists/progeny_key.txt
  real_prog_names: ../Data/Real_Data/Lists/real_prog_names.txt
  bam_list: ../Data/Real_Data/Lists/bam_list.txt

# =================================================================================================
#     Indexing params
# =================================================================================================
bwa:
  index: bwtsw

# =================================================================================================
#     Picard 
# =================================================================================================
picard:
  metrics: ../Data/Metrics/

# =================================================================================================
#     samtools options 
# =================================================================================================


# To call from this file you basicaly put brackets until you reach the variable you need
# ex: in the params part use [ref][fasta], then call it with params.x
