# =================================================================================================
#     Reference Genome
# =================================================================================================

genome: ../Data/Real_Data/Genome/tall_fescue_pv1.1.fasta
idx: 

# =================================================================================================
#     Directory Paths
# =================================================================================================
paths:
  genomepath: ../Data/Refrence
  samples_path: ../Data/Flex_Data/Sequences
  mapped_reads: ../Data/Flex_Data/Mapped_Reads
  vcfs: ../Data/Flex_Data/VCFs
  output: ../Data/Flex_Data/output
  mpileup: ../Data/Flex_Data/mpileup

# =================================================================================================
#     Indexing params
# =================================================================================================
bwa:
  index: bwtsw

# =================================================================================================
#     samtools options 
# =================================================================================================

output: ../Data/output/merged.bcf

# =================================================================================================
#     samtools options 
# =================================================================================================


# To call from this file you basicaly put brackets until you reach the variable you need
# ex: in the params part use [ref][fasta], then call it with params.x
