# =================================================================================================
#     Reference Genome
# =================================================================================================

genome: ../../Data/Flex_Data/Test/Refrence/tall_fescue_pv1.1.fasta
idx: 

# =================================================================================================
#     Directory Paths
# =================================================================================================
paths:
  genomepath: ../../Data/Refrence
  samples_path: ../../Data/Flex_Data/Test/Sequences
  mapped_reads: ../../Data/Flex_Data/Test/Mapped_Reads
  vcfs: ../../Data/Flex_Data/Test/VCFs
  mpileup: ../../Data/Flex_Data/Test/mpileup

# =================================================================================================
#     Indexing params
# =================================================================================================
bwa:
  index: bwtsw

# =================================================================================================
#     samtools options 
# =================================================================================================


# =================================================================================================
#     samtools options 
# =================================================================================================


# To call from this file you basicaly put brackets until you reach the variable you need
# ex: in the params part use [ref][fasta], then call it with params.x
